### ISSUE TITLE
<SystemTable>.after does not accept importing <SystemTable>.system

### ISSUE THREAD

**Issue by sasial-dev** [evaera/matter#24]
<SystemTable>.after does not accept importing <SystemTable>.system

```ts
import { system as dayNightCycle } from "./dayNightCycle";

export const after = [dayNightCycle];
``` 
Left me with the cannot schedule systems error, it was fixed by having to do
```ts
import * as dayNightCycle from "./dayNightCycle";

export const after = [dayNightCycle];
```

**Comment by sasial-dev** [comment]
I've tested with a plain function system and it works fine, leaving this edge case possibly deserving of it's own error?

**Comment by evaera** [comment]
This is improper usage. The system table should be placed in the `after` table.
