### ISSUE TITLE
Put example game files in a single folder

### ISSUE THREAD

**Issue by Aimarekin** [evaera/matter#33]
Matter's [example game](https://github.com/evaera/matter/tree/main/example) is missing the `example.project.json` mentioned in it's README. This file isn't created automatically by wally.

EDIT:
The project file is actually in the root of the repository - which is confusing. I'd expect all files for the example game to be located inside the example game folder, specially considering that it has files you'd normally find in a rojo project folder

**Comment by OverHash** [comment]
It's located in the root of the matter repository, https://github.com/evaera/matter/blob/bb17f5fa015f3c90676683faef6cd8118cc9583a/example.project.json

**Comment by Aimarekin** [comment]
> It's located in the root of the matter repository, https://github.com/evaera/matter/blob/bb17f5fa015f3c90676683faef6cd8118cc9583a/example.project.json

That's a bit strange - changing the topic then - I think having all the files for the example game in the example game folder would make more sense, specially considering how the example folder has the structure of a rojo project

**Comment by evaera** [comment]
No, the existing structure is correct. The model file syncs in the Matter library alongside the game, which means that the game and the example are both constituents of the example game project file, so it exists at the root level.
