### ISSUE TITLE
FPS Unlocker breaks debugger

### ISSUE THREAD

**Issue by ATK422** [evaera/matter#64]
Unsure if I should put this here or plasma, but if you have an FPS unlocker on, then it sometimes doubles the ui. This only happens on the client, not on the server.
![image](https://github.com/evaera/matter/assets/54485972/41a56161-9f24-402d-97e2-705d15bd4cdd)

**Comment by LastTalon** [comment]
Can you include the order of events being fired that causes this to happen? This is difficult for me to reproduce since I don't use that.
