### ISSUE TITLE
Slider debugger widget returns 0 when panel is closed

### ISSUE THREAD

**Issue by jackTabsCode** [evaera/matter#66]
Assuming the following code in a system...
```ts
const value = widgets.slider({
	initial: 50,
	min: 1,
	max: 100
})
```
...`value` will read 0 if the panel is not open. Once the panel is opened, the widget will return the initial value. I expect the widget to return the initial value if the panel is not open.

I'm assuming this has to do with the panel using dummy handles when the panel is closed.

**Comment by jackTabsCode** [comment]
Looks like this is not a bug.
https://eryn.io/matter/api/Debugger#getWidgets

I don't mind a checkbox or button starting with false, but a slider starting with 0 is, generally speaking, unexpected behavior. We specify an initial value in the slider's options, and it should use it when the debugger is closed. For what I was using the slider for, a value of 0 made me think there was something broken in my game.

**Comment by Ukendio** [comment]
I agree that this can be improved, have also ran into it being annoying so I will look into this soon :)
